export interface Game {
    id_game: number,
    num: number,
    primary_name: string,
    year_published: number,
    min_players: number,
    max_players: number,
    description: string,
    playing_time: number,
    min_age: number,
    owned: number,
    trading: number,
    wanting: number,
    wishing: number,
}